cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name="cart_details"),
    path('add', views.add_to_cart, name="add"),
    path('remove/<int:id>', views.remove_from_cart, name="remove"),
    path('clear/', views.clear_cart, name="clear"),
    path('front1/', views.order),
    path('front1/form', views.displayitems)
]

orders/urls.py
from orders.forms import OrderUpdateForm
from django.urls import path
from orders import views
app_name = 'orders'
urlpatterns = [
    path('place/<int:sid>/<int:oid>', views.CreateOrder.as_view(), name='place'),
    path('recommend/<str:plid>',
         views.Recommend.recommendation_algo, name='recommend'),
    path('my', views.MyOrders.as_view(), name='my'),
    path('details/<int:pk>/', views.OrderDetails.as_view(), name='details'),
    path('invoice/<int:pk>/', views.OrderInvoice.as_view(), name='invoice'),
    path('rating/<int:pk>', views.OrderRating.add_review, name='rating'),
    path('redirectupdateorder',views.UpdateOrder)
]

store/urls.py
from django.conf.urls import url
from django.urls import re_path
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('categories', views.CategoriesList.as_view(), name='categories_list'),
    path('product/<slug:slug>/', views.ProdcutDetails.as_view(),
         name='product_details'),
    re_path(r'^user/location/$', views.save_user_geolocation),
    #url(r'^reviews/', include('reviews.urls', namespace="reviews")),
]

orders/models.py
from django.db import models
from django.conf import settings
from store.models import Product, Store
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE


# Create your models here.

choices = (
    ('Requested', 'Requested'),
    ('Pending', 'Pending'),
    ('Accepted', 'Accepted'),
    ('Packed', 'Packed'),
    ('Shipped', 'Shipped'),
    ('Delivered', 'Delivered')
)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='orders', on_delete=models.CASCADE)
    store = models.ForeignKey(
        Store, on_delete=models.CASCADE, related_name='reviews', default=0)
    address = models.CharField(max_length=150, blank=False, null=False)

    pin_code = models.CharField(max_length=10)
    city = models.CharField(max_length=50)
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        choices=choices, max_length=10, default='Pending')
    total_price = models.FloatField(null=False, blank=False)
    rating = models.IntegerField(default=0)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_absolute_url(self):
        return reverse('orders:invoice', kwargs={'pk': self.pk})


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name='ordered', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    total = models.FloatField(null=False, blank=False)

    def __str__(self):
        return f'Order Item {self.id}'


class Recommendations(models.Model):
    shop = models.TextField(null=False, blank=False)
    score = models.FloatField(null=False, blank=False)
    accepted = models.BooleanField(default=False)
    order_time = models.DateTimeField(auto_now=True)
    status = models.CharField(
        choices=choices, max_length=10, default='Pending')


class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    order = models.ForeignKey(
        Order, related_name='reviews', on_delete=models.CASCADE)
    userrating = models.IntegerField(choices=RATING_CHOICES)


class AcceptedOrderItem(models.Model):
    shop = models.ForeignKey(Store, on_delete=models.CASCADE)
    orderitem = models.ForeignKey(OrderItem, on_delete=models.CASCADE)

class RejectedOrder(models.Model):
    shop = models.ForeignKey(Store, on_delete=models.CASCADE,default=0)
    order = models.ForeignKey(Order, on_delete=models.CASCADE,default=0)

# class UserAddress(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     address = models.CharField(max_length=1000)
#     pincode = models.CharField(max_length=7)
#     city = models.CharField(max_length=255)
#     lat = models.FloatField()
#     long = models.FloatField()

orders/forms.py
from django.forms import widgets
from django.forms.widgets import Widget
from orders.models import Order, Review
from django import forms
from django.contrib.auth.models import User


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['address', 'city', 'pin_code']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['userrating']


class OrderUpdateForm(forms.Form):
    sid = forms.CharField(max_length=1000,widget=forms.HiddenInput())
    oid = forms.CharField(max_length=1000,widget=forms.HiddenInput())

orders/views.py
from django.shortcuts import render, redirect, Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.views import generic
from orders.forms import OrderForm, ReviewForm,OrderUpdateForm
from orders.models import Order, OrderItem, Review
from cart.cart import Cart
from django.db.models import Count
import store
from store.models import Product, Store
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from recommendation_engine import *
import subprocess
# Create your views here.
import recommendation_engine
from orders.models import Recommendations
import json
import math
import os
import django
import requests
from django.db.models import Max, Min
from store import models
from time import sleep

class CreateOrder(LoginRequiredMixin, generic.CreateView):
    form_class = OrderForm
    template_name = 'orders/place_order.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = Cart(self.request)
        products = Product.objects.filter(pk__in=cart.cart.keys())
        cart_items = map(
            lambda p: {'product': p, 'quantity': cart.cart[str(p.id)]['quantity'], 'total': p.price*cart.cart[str(p.id)]['quantity']}, products)
        context['summary'] = cart_items
        return context

    def form_valid(self, form):
        cart = Cart(self.request)
        if len(cart) == 0:
            return redirect('cart:cart_details')
        order = form.save(commit=False)
        order.user = self.request.user
        store = Store.objects.get(id=660453821292455697)
        order.store = store
        order.total_price = cart.get_total_price()
        order.save()
        products = Product.objects.filter(id__in=cart.cart.keys())
        orderitems = []
        for i in products:
            q = cart.cart[str(i.id)]['quantity']
            orderitems.append(
                OrderItem(order=order, product=i, quantity=q, total=q*i.price))
        OrderItem.objects.bulk_create(orderitems)
        cart.clear()
        messages.success(self.request, 'Your order is successfully forwarded to FreshExpress Store .')
       # os.system('python3 recommendation_engine.py')
        return redirect('store:product_list')


class MyOrders(LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = 'orders/order_list.html'
    context_object_name = 'orders'
    paginate_by = 20

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).order_by('-created').annotate(total_items=Count('items'))


class OrderDetails(LoginRequiredMixin, generic.DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'orders/order_details.html'

    def get_queryset(self, **kwargs):
        objs = super().get_queryset(**kwargs)
        return objs.filter(user=self.request.user).prefetch_related('items', 'items__product')


class OrderInvoice(LoginRequiredMixin, generic.DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'orders/order_invoice.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.prefetch_related('items', 'items__product')

    def get_object(self, **kwargs):
        obj = super().get_object(**kwargs)
        if obj.user_id == self.request.user.id or self.request.user.is_superuser:
            return obj
        raise Http404


class Recommend(LoginRequiredMixin):
    def recommendation_algo(request, **kwargs):
        plid = kwargs['plid']
        result = recommendation_engine.recommendation_algo(plid, request)
        form = OrderUpdateForm()
        return render(request, 'orders/show_view.html', context={'result': result,'form':form})
       # print(output)


class OrderRating(LoginRequiredMixin, generic.DetailView):
    def add_review(request, **kwargs):
        order = get_object_or_404(Order, **kwargs)
        form = ReviewForm(request.POST)
        if form.is_valid():
            object = form.save(commit=False)
            object.order = order
            try:
                ob2=Review.objects.filter(order=order)[0]
                ob2.userrating=object.userrating
                ob2.save()
            except:    
                object.save()
            result = recommendation_engine.ratingupdater()
            print("inside views:" + str(result))
        else:
            print(form)
        return render(request, 'orders/order_list.html', {'order': order, 'form': form})


def UpdateOrder(request):
    form = OrderUpdateForm(request.POST)
    if form.is_valid():
        try:
            order = Order.objects.get(id=form.cleaned_data['oid'])
            shop = Store.objects.get(id=form.cleaned_data['sid'])
            order.store = shop
            order.status = "Pending"
            order.paid = True
            order.save()
            print("Store object updated successfully")
            messages.success(request, 'Your order is successfully placed.')
            cart = Cart(request)
            cart.clear()
        except:
            print("Error while updating the store..check logs")
    else:
        print("form is invalid")
    return redirect('store:product_list')
    

orders/templates/orders/order_details.html
{% extends 'base.html' %} {% load thumbnail %} {% block title %} Order no -
{{order.id}} {% endblock title %} {% block content %}
<h2 class="mt-4">Order id - {{order.id}}</h2>
{% comment %}
<h4 class="font-weight-light">
  {{order.user.first_name|default:order.user.username}} {{order.user.last_name}}
</h4>
{% endcomment %}
<h4>
  {% if order.paid %}
  <span class="badge badge-success">Paid</span>
  {% else %}
  <span class="badge badge-danger">Payment Pending</span>
  {% endif %}
</h4>
<h5 class="font-weight-light">
  Delivery Address - {{order.address}}, {{order.city}}, {{order.pin_code}}
</h5>
<h5 class="font-weight-light">Status - {{order.status}}</h5>
<h5 class="font-weight-light">Placed on - {{order.created}}</h5>
<h3 class="font-weight-light mt-4">Items</h3>
<ul class="list-group shadow-sm">
  {% for o in order.items.all %}
  <li
    class="
      list-group-item
      d-flex
      align-items-center
      justify-content-between
      flex-column flex-md-row
    "
  >
    <div class="d-flex align-items-center">
      <img
        src="{% thumbnail o.product.image 75x0 %}"
        alt="{{o.product.name}}"
        class="img-fluid"
      />
      <h5 class="ml-3 mb-0 font-weight-light">
        <a href="{{o.product.get_absolute_url}}">{{o.product.name}}</a>
      </h5>
    </div>
    <h5 class="font-weight-light mb-0">
      Rs.{{o.product.price}} * {{o.quantity}} = <b>Rs.{{o.total}}</b>
    </h5>
  </li>
  {% endfor %}
  <li class="list-group-item bg-primary text-white">
    <h5 class="mb-0 text-right font-weight-light">
      Total - <b>Rs.{{order.total_price}}</b>
    </h5>
  </li>

  {% if order.status == 'Delivered' %}
  {% load static %} 
  <link rel="stylesheet" href="{% static 'css/rating.css' %}">
  <form method="POST" class="rating" action="{% url 'orders:rating' order.id %}">{%csrf_token %}
    
    <label>
    <input type="radio" id="5-star" name="userrating" value="1" />
    <span class="icon">★</span>
  </label>
  <label>
    <input type="radio" id="2-star" name="userrating" value="2" />
    <span class="icon">★</span>
    <span class="icon">★</span>
  </label>
  <label>
    <input type="radio" id="3-star" name="userrating" value="3" />
    <span class="icon">★</span>
    <span class="icon">★</span>
    <span class="icon">★</span>   
  </label>
  <label>
    <input type="radio" id="4-star" name="userrating" value="4" />
    <span class="icon">★</span>
    <span class="icon">★</span>
    <span class="icon">★</span>
    <span class="icon">★</span>
  </label>
  <label>
    <input type="radio" id="5-star" name="userrating" value="5" />
    <span class="icon">★</span>
    <span class="icon">★</span>
    <span class="icon">★</span>
    <span class="icon">★</span>
    <span class="icon">★</span>
  </label>
  <script>
    $(':radio').change(function() {
      console.log(this.value);
    });
    </script>
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
     &nbsp;&nbsp;
     <button type="submit" class="btn btn-success" value="Rate">Rate</button>   
</form>
  {% endif %}

</ul>
<p class="my-2 text-center">
  {% if order.paid %}
  <a href="{{order.get_absolute_url}}" class="btn btn-success">Invoice</a>
  {% else %}
  <a
    href="#"
    class="btn btn-success btn-lg disabled"
    role="button"
    aria-disabled="true"
    >Invoice</a
  >
  {% endif %}
</p>

{% endblock content %}

orders/templates/orders/order_invoice.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Invoice Order - {{order.id}}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    />
  </head>
  <body>
    <div class="container my-4">
      <h2>Order id - {{order.id}}</h2>
      <h4 class="mb-3">
        To - {{order.user.first_name|default:order.user.username}}
        {{order.user.last_name}}
      </h4>
      <h4 class="font-weight-light">{{order.address}}</h4>
      <h4 class="font-weight-light mb-3">{{order.city}}, {{order.pin_code}}</h4>
      <h5 class="font-weight-light mb-4">Placed on {{order.created}}</h5>
      <hr />
      <table class="table table-striped mt-4">
        <thead class="table-dark">
          <tr>
            <td>Name</td>
            <td>Unit Price</td>
            <td>Quantity</td>
            <td>Total</td>
          </tr>
        </thead>
        <tbody>
          {% for o in order.items.all %}
          <tr>
            <td>{{o.product.name}}</td>
            <td>Rs.{{o.product.price}}</td>
            <td>{{o.quantity}}</td>
            <td>Rs.{{o.total}}</td>
          </tr>
          {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"></td>
            <td class="text-right">Grand Total -</td>
            <td>
              <b>Rs.{{order.total_price}}</b>
            </td>
          </tr>
        </tfoot>
      </table>
      <h5>
        Payment status - {% if order.paid %}
        <span class="badge badge-success">Paid</span>
        {% else %}
        <span class="badge badge-danger">Payment Pending</span>
        {% endif %}
      </h5>
      <h5>Payment mode - Cash on delivery</h5>
      <h5>Status - {{order.status}}</h5>
    </div>
    <footer class="text-center d-print-none">
      <button class="btn btn-primary" onclick="window.print()">Print</button>
      <button class="btn btn-danger" onclick="history.back()">Go Back</button>
    </footer>
  </body>
</html>

orders/templates/orders/order_list.html
{% extends 'base.html' %} {% block title %}Your Orders {% endblock title %}
{% block content %}
<h1 class="font-weight-light mt-3">Your Orders</h1>
<hr />
<ul class="list-group my-3">
  {% for order in orders %}
  <li class="list-group-item">
    <h5 class="mb-2">
      {% if order.status == 'Delivered' %}
      <span class="badge badge-success font-weight-light">
        {{order.status}}
      </span>
      {% else %}
      <span class="badge badge-info font-weight-light">{{order.status}}</span>
      {% endif %}
    </h5>
    <h3>
      <a href="{% url 'orders:details' order.id %}">Order id - {{order.id}}</a>
    </h3>
    <h5>Rs.{{order.total_price}}</h5>
    <p class="mb-0">{{order.total_items}} Items</p>
    <p class="mb-0">
      Delivery Address - {{order.address}}, {{order.city}}, {{order.pin_code}}
    </p>
    <p class="mb-0">Placed {{order.created|timesince}} ago.</p>
  </li>
  {% empty %}
  <li class="list-group-item text-center border-white">
    <h3 class="font-weight-light">You haven't placed any orders.</h3>
    <a href="{% url 'store:product_list' %}" class="btn btn-secondary">
      Continue Shopping
    </a>
  </li>
  {% endfor %}
</ul>
{% with page_obj as page %}
<p>Page <b>{{page.number}}</b> of <b>{{page.paginator.num_pages}}</b></p>
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a href="?page={{page.previous_page_number}}" class="page-link">
        Previous
      </a>
    </li>
    {% endif %}
    <li class="page-item active"><a href="#" class="page-link">1</a></li>
    {% if page.has_next %}
    <li class="page-item">
      <a href="?page={{page.next_page_number}}" class="page-link">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endwith %} {% endblock content %}

orders/templates/orders/place_order.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block title %} Place
Order {% endblock title %} {% block content %}
<div class="row my-3">
  <div class="col-md-6 col-12 mb-3">
    <div class="card">
      <h3 class="card-header mb-0">Order Summary</h3>
      <div class="card-body">
        {% for i in summary %}
        <p class="card-text d-flex justify-content-between mb-2">
          <span class="d-block"> {{i.quantity}} x {{i.product.name}} </span>
          <span class="d-block">Rs.{{i.total}}</span>
        </p>
        {% empty %}
        <h5 class="card-text font-weight-light">No items in cart.</h5>
        {% endfor %}
        <h4 class="card-text text-right">
          <span class="badge badge-primary">
            Grand Total - <b>Rs.{{cart.get_total_price}}</b>
          </span>
        </h4>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-12">
    <div class="card card-body">
      <h3 class="mb-3">Shipping Details</h3>
      <form method="POST">
        {% csrf_token %} {{form|crispy}} {% if cart.empty %}
        <div class="alert alert-danger my-2">Your cart is empty.</div>
        <button disabled class="btn btn-success">Place Order</button>
        {% else %}
        <button type="submit" class="btn btn-success">Place Order</button>
        {% endif %}
      </form>
    </div>
  </div>
</div>
{% endblock content %}

orders/templates/orders/show_view.html
{% extends 'base.html' %}
{% load static %}
{% block javascript %}

{% endblock %}
{% block content %}
<meta http-equiv="refresh" content="10">
  <div class="container">
    <h2 class="text-center">Choose your favorite Shop</h2>
    <div class="row">
      {% for i,j in result.items %}
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
        <div class="card" style="margin-bottom: 20px;">
        <div class="card-block">
         <figure>
            <img src="/static/shop.jpeg" alt="Trulli" style="width:100%;height:30%">
            <figcaption style="text-align: center;">{{i}}</figcaption>
         </figure>
         </div>


         <div style="margin:auto">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-x  awesome/4.7.0/css/font-awesome.min.css">
          <style>
            .checked {
            color: orange;
                    }
          </style>
          <span class="fa fa-star checked">{{j.0}}</span>
         </div>
         <div style="margin:auto">
         {%if j.2 and j.3%}
         <h6>Items Available-{{j.2}}{{"/"}}{{j.3}}</h6>
           {%else%}
         <h6>Items Available-None</h6>  
         {%endif%}
         </div>

         
         <div style="margin:auto">
          {%with sid=j.1%}
          {%with oid=j.4%}
           <!---- <a href="{% url 'orders:place' sid oid %}" class="btn btn-success">Checkout</a>-->
            <form action="../redirectupdateorder" method="POST">
              {% csrf_token %}
              <input type="hidden" name="oid" value="{{oid}}">
              <input type="hidden" name="sid" value="{{sid}}">
              <input type="submit" value="Checkout" class="btn btn-success">
            </form>  
          {%endwith%}
          {%endwith%}
          </div>
    

        
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}