cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name="cart_details"),
    path('add', views.add_to_cart, name="add"),
    path('remove/<int:id>', views.remove_from_cart, name="remove"),
    path('clear/', views.clear_cart, name="clear"),
    path('front1/', views.order),
    path('front1/form', views.displayitems)
]

shopadmin/urls.py
from os import name
from shopadmin.inventoryviews import redirectremoveitems
from django.urls import path
from . import views

app_name = 'shopadmin'
urlpatterns = [
    path('', views.index),
    path('store', views.storehome,name='store'),
    path('inventory', views.inventoryhome,name='inventory'),
    path('redirectstore', views.redirecthome,name='redirectstore'),
    path('redirectinventory', views.redirectinventory,name='redirectinventory'),
    path('redirectadditem', views.redirectadditems,name='redirectadditem'),
    path('redirectremoveitem', views.redirectremoveitems,name='redirectremoveitem'),
    path('receivedorders', views.ReceivedOrders,name='receivedorders'),
    path('redirectreceivedorders', views.RedirectReceivedOrders,name='redirectreceivedorders'),
    path('acceptedorders', views.AcceptedOrders,name='acceptedorders'),
]

store/urls.py
from django.conf.urls import url
from django.urls import re_path
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('categories', views.CategoriesList.as_view(), name='categories_list'),
    path('product/<slug:slug>/', views.ProdcutDetails.as_view(),
         name='product_details'),
    re_path(r'^user/location/$', views.save_user_geolocation),
    #url(r'^reviews/', include('reviews.urls', namespace="reviews")),
]

shopadmin/models.py
from django.db import models

# Create your models here.

shopadmin/views.py
from django.db.models.query import FlatValuesListIterable
from django.http.response import HttpResponse
from django.shortcuts import render
from orders.models import Order, OrderItem,AcceptedOrderItem,RejectedOrder
from store.models import Product
from .inventoryviews import *
from django.views.generic.list import ListView
from django.core.paginator import Paginator
from django.forms import formset_factory
from .inventoryforms import OrderItemForm,DeliveredForm
import smtplib, ssl
# Create your views here.


def index(request):
    orderlist = {}
    allorders = Order.objects.all()
    for singleorder in allorders:
        li = list(OrderItem.objects.filter(
            order=singleorder).values_list('product__name', flat=True))
        orderlist[singleorder.id] = li
    context = {'li': orderlist}
    return render(request, 'index4.html', context)


class OrdersList(ListView):
    paginate_by = 5
    queryset = Order.objects.prefetch_related('id').all()
    context_object_name = 'Orderlist'


@login_required
def AcceptedOrders(request):
    try:
        shop = Store.objects.filter(merchant__user=request.user)[0]
        merchant = True
    except:
        print("current user does not have any shops, return to the home page")
        return HttpResponseRedirect('/shopadmin')
    #fetch the orders from the orders whose status is Accepted  (change it to new)
    form = DeliveredForm(request.POST)
    if form.is_valid():
        try:
            order = Order.objects.get(pk=form.cleaned_data['order'])
            order.status = "Delivered"
            order.save()
        except:
            print("current order does not exist")
    else:
        print("form is invalid")

    orders = Order.objects.filter(store=shop,status="Pending")
    print(orders)
    allorderslist = []
    for order in orders:
        orderlist = {}
        orderitems = AcceptedOrderItem.objects.filter(shop=shop,orderitem__order=order)
        if(len(orderitems)!=0):
            orderlist['order'] = order
            orderlist['items'] = orderitems
            allorderslist.append(orderlist)
    print(allorderslist)
    paginator = Paginator(allorderslist, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj':page_obj,'merchant':merchant}
    return render(request, 'current_orders.html', context)


@login_required
def ReceivedOrders(request):
    # fetch the orders which are releavnt to the current shop
    try:
        shop = Store.objects.filter(merchant__user=request.user)[0]
    except:
        print("current user does not have any shops, return to the home page")
        return HttpResponseRedirect('/shopadmin')
    #get the list of the orders which are already worked on 
    accepted = AcceptedOrderItem.objects.filter(shop=shop).values_list('orderitem__order__id').distinct()
    rejected = RejectedOrder.objects.filter(shop=shop).values_list('order__id')
    #get the valid orders for the shop
    allorders = Order.objects.filter(status="Requested").exclude(pk__in=accepted).exclude(pk__in=rejected)
    print(allorders)
    orderlist = []
    #fetcht the items present for the current owner
    present = StoreItem.objects.filter(shop=shop,status=True).values_list('product__id',flat=True)
    for order in allorders:
        # only fetch the items which are available to the shopkeeper
        li = OrderItem.objects.filter(order=order,product__id__in=present).values('product__name', 'id','order__id','product__id','quantity')
        if(len(list(li))!=0):
            idlist = li.values('id')
            li = list(li)
            orderlist.append(li)
    paginator = Paginator(orderlist, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj, 'present': present}
    return render(request, 'received.html', context)


@login_required
def RedirectReceivedOrders(request):
    form = OrderItemForm(request.POST)
    try:
        shop = Store.objects.filter(merchant__user=request.user)[0]
    except:
        print("current user does not have any shops, return to the previous page")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    if form.is_valid():
        # if request is accepted by the store owner
        if('Accept' in request.POST):
            # fetch the orderitems of the selected orders
            items = form.cleaned_data['orderitems']
            orderitems = items.split('_')
            # if no values are accepted return
            if(items == ""):
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            items = OrderItem.objects.filter(pk__in=orderitems)
            for item in items:
                ob = AcceptedOrderItem(shop=shop, orderitem=item)
                ob.save()
            # store the given order items in the db
        else:
            try:
                orderid = form.cleaned_data['orderid']
                orderob = Order.objects.get(id=orderid)
                r= RejectedOrder(order= orderob,shop=shop)
                r.save()
            except:
                print("error while inserting rejected order")
    else:
        print("form is invalid")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def support(request):
    return render(request,'support.html')

shopadmin/templates/current_orders.html
{% extends 'base.html' %} {% load thumbnail %} {% block title %} Accepted Orders
{{order.id}} {% endblock title %} 

{% block javascript %}

{% endblock javascript %}
{% block content %}

<br><br>

{% if page_obj %}
<table class="table table-striped table-bordered"> 
    <tr><th><center>Order ID</center></th><th><center>Order Items</center></th><th><center>Address</center></th><th><center>Price</center></th> <th><center>Payment Status</center></th><th><center>Mark Delivered</center></th><th>Order Placed Date</th></tr>
    {% for order in page_obj %}
    <tr>
        <td><center>{{order.order.id}}</center></td>
        <td>
            {% for item in order.items %}
                {{item.orderitem.product.name}}|Qty:({{item.orderitem.quantity}})<br>
            {% endfor %}
        </td>
        <td>
            {{order.order.user}}<br>
            {{order.order.user.first_name}} {{order.order.user.last_name}}<br>
           {{order.order.address}},{{order.order.city}} - {{order.order.pin_code}}
        </td>
        <td>{{order.order.total_price}}</td>
        <td>
            {% if order.order.paid %}
                Paid
            {% else %}
                Not Paid
            {% endif%}
        </td>
        <td>
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" value="{{order.order.id}}" name="order">
                <input type="submit" value="Delivered" class="btn btn-success">
            </form>
        </td>
        <td>
            {{order.order.created}}
        </td>
    </tr>
    {% endfor %}
</table>
{%  else %}
<br><br>
<div class="alert alert-info" role="alert">
    <h3>No orders are currently present for delivery. <br> Sit back and relax, we will notify you once we receive the order!!</h3>
  </div>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock content %}

shopadmin/templates/inventory.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% load thumbnail %}
{%block title %}Store{% endblock title %}
{%block content %}
<div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
  
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Add Items</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
  
        <!-- Modal body -->
        <div class="modal-body">
          {% load crispy_forms_tags %}
              <form action="{% url 'shopadmin:redirectadditem' %}" method="post">
                {% csrf_token %}
                {{ form | crispy}}
                <input type="submit" value="Submit">
              </form>
        </div>
  
      </div>
    </div>
  </div>
<div class="row mt-3">
    <div class="col-lg-3 col-md-6 col-12 mb-3">
      <div class="card card-body p-3 shadow-sm">
        <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#myModal">
            Add Item
          </button>
          <br><br><center>
              &nbsp;<br>
            Total Orders: {{total_orders}}<br>
          Ratings: {{rating}} <br>
          </center>
          
      </div>
    </div>
    <div class="col-lg-9 col-md-6 col-12">
      <h2 class="font-weight-light mb-2">Products</h2>
      <hr />
      <div class="row">
        {% for product in page_obj %}
        <div class="col-lg-4 col-12 mb-2 px-sm-1">
          <div class="card shadow-sm h-100">
            <img
              src="{% thumbnail product.product.image 0x250 %}"
              alt="No Image"
              class="img-aspect p-2"
            />
            <div class="card-body">
              <h6 class="card-subtitle font-weight-light">
                <a href="{% url 'store:product_details' product.product.slug %}""
                  >{{product.product.name}}</a>
              </h3>
              <h4 class="card-text">
                <span class="badge badge-warning">Rs.{{product.product.price}}</span>
              </h4>
              
              <form action="{% url 'shopadmin:redirectinventory' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="productid" value="{{product.id}}">
                <div class="custom-control custom-switch custom-switch-lg">
                    <input type="checkbox" name="status" class="custom-control-input" id="p{{product.id}}" {% if product.status %} checked {% endif %} onchange="this.form.submit()">
                    <label class="custom-control-label" for="p{{product.id}}" ><p class="card-text">{{product.product.description|truncatewords:10 }}</p></label>
                </div>
              </form>
              
            </div>
          </div>
        </div>
        {% empty %}
        <div class="col-12 text-center">
          <h3 class="font-weight-light my-4 py-4">No products found.</h3>
        </div>
        {% endfor %}
      </div>
      
      <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    

    {% endblock %}

shopadmin/templates/received.html
{% extends 'base.html' %} {% load thumbnail %} {% block title %} Received Orders
{{order.id}} {% endblock title %} 

{% block javascript %}

<meta http-equiv="refresh" content="45"> <!-- refresh the page every 45 seconds-->
<script type="text/javascript">
    function codeAddress() {
        
       //get the orderelements from the page
       var orderelements = document.getElementsByClassName("order");
    
       for(var i=0;i<orderelements.length;i++){
            
            console.log(orderelements[i].id);
            //get the orderitem elements for the particular order
            orderelements[i].value ="";
            var orderitems = document.getElementsByClassName(orderelements[i].id);
            for( var j=0;j<orderitems.length;j++){
                if(orderitems[j].checked == true){
                    console.log(orderitems[j]);
                    if(orderelements[i].value !="")
                    orderelements[i].value += ("_");
                    orderelements[i].value += (orderitems[j].name);
                    
                }
                
            }
       }
    }
    window.onload = codeAddress;
    </script>
{% endblock javascript %}
{% block content %}

<br><br>

{% if page_obj %}
<table class="table table-striped table-bordered"> 
    <tr><th><center>Order Items</center></th> <th colspan="2">Decision</th></tr>
{% for orderid in page_obj %}
<tr>
      <td>
          
        {% for item in orderid %}
            <input type="checkbox" name="{{item.id}}" class="order{{item.order__id}}" {%if item.product__id in present %} checked {% endif %} onclick="codeAddress()"> {{item.product__name}} {{item.product__id}}|Qty:{{item.quantity}} <br>
        {% endfor %}
        <form action="{% url 'shopadmin:redirectreceivedorders' %}" method="POST"> 
            {% csrf_token %}
        <input type="text" id="order{{orderid.0.order__id}}" name="orderitems" class="order" value="" hidden >
        <input type="text" id="orderid" name="orderid" value="{{orderid.0.order__id}}" hidden>
    </td>
    <td colspan="2">
        <div class="row text-center">
            <div class="col-md-6"><input type="submit" name='Accept' value="Accept" class="btn btn-success">&nbsp; </div>
            <div class="col-md-6"><input type="submit" name ='Reject' value="Reject" class="btn btn-danger"> &nbsp;</div>&nbsp;
        </div>
        
        
    </td>
    </form>
</tr>
{% endfor %}
</table>
{%  else %}
<br><br>
<div class="alert alert-info" role="alert">
    <h3>No orders are currently present for your shop. <br> Sit back and relax, we will notify you once we receive the order!!</h3>
  </div>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock content %}

shopadmin/templates/storeinfo.html
{% extends 'base.html' %} {% load thumbnail %} {% block title %} Store Info {% endblock title %} 
{% block javascript %}

{% endblock javascript %}
{% block content %}
{% load crispy_forms_tags %}
<br><br>
<h3>Please enter the your latest store information. </h3>
<small>Note: One merchant account can only have one store.</small><br><br>
<form action="" method="post">
                {% csrf_token %}
                {{ form | crispy}}
    <input type="submit" value="Update/Add" class="btn btn-success">
</form>

{% endblock content %}

shopadmin/templates/temp.html
<h1>shailesh</h1>

<ul>
{% for orderid,orderitems in orderdict.items %}

{{orderid}}
 {% for item in orderitems %}
 {{item.product__name}}
 {{item.id}}
 {% endfor %}
{% endfor %}

</ul>
<ul>
{% for orderid in page_obj %}
    
    <li>{{ orderid }}</li>
    <br>
{% endfor %}
</ul>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>