accounts/urls.py
from os import name
import shopadmin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.profile, name='profile'),
    path('shopadmin/',include('shopadmin.urls',namespace='shopadmin')),
    path('address',views.changeAddress,name='address'),
    path('help',views.help,name="help")
]

cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name="cart_details"),
    path('add', views.add_to_cart, name="add"),
    path('remove/<int:id>', views.remove_from_cart, name="remove"),
    path('clear/', views.clear_cart, name="clear"),
    path('front1/', views.order),
    path('front1/form', views.displayitems)
]

orders/urls.py
from orders.forms import OrderUpdateForm
from django.urls import path
from orders import views
app_name = 'orders'
urlpatterns = [
    path('place/<int:sid>/<int:oid>', views.CreateOrder.as_view(), name='place'),
    path('recommend/<str:plid>',
         views.Recommend.recommendation_algo, name='recommend'),
    path('my', views.MyOrders.as_view(), name='my'),
    path('details/<int:pk>/', views.OrderDetails.as_view(), name='details'),
    path('invoice/<int:pk>/', views.OrderInvoice.as_view(), name='invoice'),
    path('rating/<int:pk>', views.OrderRating.add_review, name='rating'),
    path('redirectupdateorder',views.UpdateOrder)
]

shopadmin/urls.py
from os import name
from shopadmin.inventoryviews import redirectremoveitems
from django.urls import path
from . import views

app_name = 'shopadmin'
urlpatterns = [
    path('', views.index),
    path('store', views.storehome,name='store'),
    path('inventory', views.inventoryhome,name='inventory'),
    path('redirectstore', views.redirecthome,name='redirectstore'),
    path('redirectinventory', views.redirectinventory,name='redirectinventory'),
    path('redirectadditem', views.redirectadditems,name='redirectadditem'),
    path('redirectremoveitem', views.redirectremoveitems,name='redirectremoveitem'),
    path('receivedorders', views.ReceivedOrders,name='receivedorders'),
    path('redirectreceivedorders', views.RedirectReceivedOrders,name='redirectreceivedorders'),
    path('acceptedorders', views.AcceptedOrders,name='acceptedorders'),
]

store/urls.py
from django.conf.urls import url
from django.urls import re_path
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('categories', views.CategoriesList.as_view(), name='categories_list'),
    path('product/<slug:slug>/', views.ProdcutDetails.as_view(),
         name='product_details'),
    re_path(r'^user/location/$', views.save_user_geolocation),
    #url(r'^reviews/', include('reviews.urls', namespace="reviews")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=1000)
    pincode = models.CharField(max_length=7)
    city = models.CharField(max_length=255)
    lat = models.FloatField(default=17.41710876415962)
    long = models.FloatField(default=78.44529794540337)

store/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE, SET_NULL
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.


class Category(models.Model):
    name = models.TextField(max_length=50, null=False, blank=False)
    slug = models.SlugField(unique=True, max_length=100, db_index=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_path(self):
        return reverse('store:product_list') + f'?category={self.id}'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='products')
    name = models.TextField(max_length=100, null=False, blank=False)
    slug = models.SlugField(unique_for_date='created')
    description = models.TextField(null=False, blank=False)
    price = models.FloatField(null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='media/products/%Y/%m/%d/', blank=True)
    availibility = models.BooleanField(null=False, default=True)

    class Meta:
        index_together = ('id', 'slug')
        ordering = ('-created',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_details', kwargs={'slug': self.slug})


class Merchant(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    joindate = models.DateField()


choices = (
    ('Open', 'Open'),
    ('Closed', 'Closed')
)


class Store(models.Model):
    name = models.CharField(max_length=1000)
    address = models.CharField(max_length=1000)
    contact = models.CharField(max_length=13)
    lat = models.FloatField()
    long = models.FloatField()
    start = models.TimeField()
    end = models.TimeField()
    gst = models.CharField(max_length=1000)
    merchant = models.ForeignKey(Merchant, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    total_orders = models.IntegerField(default=0)
    shop_status = models.CharField(
        choices=choices, max_length=10, default='Open')


class StoreItem(models.Model):
    shop = models.ForeignKey(Store, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)


class UserGeoLocation(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE)
    latitude = models.FloatField(blank=False, null=False)
    longitude = models.FloatField(blank=False, null=False)

accounts/forms.py
from accounts.models import UserAddress
from django import forms
from .models import UserAddress

class UserAddressForm(forms.ModelForm):
    class Meta:
        model = UserAddress
        fields = ['address', 'city', 'pincode']

accounts/views.py
from accounts.models import UserAddress
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.forms import modelform_factory, widgets
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .forms import UserAddressForm
from django.http.response import HttpResponse
from django.contrib import messages
from django.http import HttpResponseRedirect
import smtplib, ssl
# Create your views here.


class Register(SuccessMessageMixin, generic.CreateView):
    form_class = UserCreationForm
    success_message = "Registration Successfull you can now login."
    template_name = "registration/register.html"
    success_url = reverse_lazy('login')


@login_required
def profile(req):
    UserEditForm = modelform_factory(
        get_user_model(), fields=('first_name', 'last_name', 'username'))
    form = UserEditForm(instance=req.user)
    if req.method == "POST":
        form = UserEditForm(instance=req.user, data=req.POST)
        if form.is_valid():
            form.save()
    return render(req, 'registration/profile.html', {'form': form})


@login_required
def changeAddress(request):
    form = UserAddressForm(request.POST)
    if form.is_valid():
        addr = form.save(commit=False)
        addr.user = request.user
        try:
            addr2 = UserAddress.objects.filter(user=request.user)[0]
            addr2.city  = addr.city
            addr2.pincode = addr.pincode
            addr2.address = addr.address
            addr2.save()
        except:
            addr.save()
    try:
        addr2 = UserAddress.objects.filter(user=request.user)[0]
        form = UserAddressForm(initial={'city':addr2.city,'pincode':addr2.pincode,'address':addr2.address})
    except:
        pass
    return render(request, 'useraddress.html', {'form': form})

def send(username,email,queries):
    email_id="guptahimanshu2035@gmail.com"
    password="ajyfgrezutgkypdd"
    try:
        subject ="""\
        Support FreshExpress
        """
        text="""\
        Greetings from FreshExpress,
        We have received your query regarding"{1}".Our Customer Support Executive will contact you soon.
        
        Thank you for using FreshExpress.
        Stay safe and stay connected!!
        Sincerly,
        The FreshExpress Service Team
        """.format(username,queries)
        conn=smtplib.SMTP('imap.gmail.com',587)
        conn.ehlo()
        conn.starttls()
        conn.login(email_id,password)
        message = 'Subject: {}\n\n{}'.format(subject, text)
        conn.sendmail(email_id,email,message)
        return 1
    except KeyError:
        return 0

def help(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        email=request.POST.get('email')
        queries=request.POST.get('queries')
        result=send(username,email,queries)
        if result==1:
            messages.success(request, "Your query is successfully registered. We will connect with you shortly!")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

store/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, HttpResponse
from django.views import generic
from django.views.generic.list import ListView
from store.models import Product, Category
from django_filters.views import FilterView
from store.filters import ProductFilter
from store.models import UserGeoLocation
from cart.forms import CartForm
from django.db.models import Count
from .viewsa import CategoriesList
from orders.models import Order

# Create your views here.


class ProductList(FilterView):
    model = Product
    queryset = Product.objects.all()
    paginate_by = 20
    filterset_class = ProductFilter
    context_object_name = 'products'
    template_name = 'store/product_list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if 'category_slug' in self.kwargs:
            qs = qs.filter(category__slug=self.kwargs['category_slug'])
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ProdcutDetails(generic.DetailView):
    model = Product
    template_name = 'store/product_details.html'
    context_object_name = 'product'

    def get_queryset(self):
        product = super().get_queryset()
        return product.select_related('category').annotate(
            total_purchases=Count('ordered'))


# class CategoriesList(generic.ListView):
#     template_name = 'store/categories_list.html'
#     context_object_name = 'categories'
#     queryset = Category.objects.all().annotate(num_products=Count('products'))

def save_user_geolocation(request):
    if request.method == 'POST':
        latitude = request.POST['lat']
        longitude = request.POST['long']
        print(latitude, longitude)
        UserGeoLocation.create(
            user=request.user,
            latitude=latitude,
            longitude=longitude,
        )
        UserGeoLocation.save()
    return HttpResponse('')

accounts/templates/allitems.html
{% extends "layouts/base.html" %}

{% block title %} Contacts {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini {% endblock body_class %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">
    <style>
       .custom-control-input:checked ~ .custom-control-label::before {
  background-color: green;
  border-color: darken(green, 10%);
}

//---------------CUSTOM SIZE STYLING---------------//

// Add class `.custom-switch-lg` to a `custom-switch`
.custom-switch.custom-switch-lg {
  padding-bottom: 1rem;
	padding-left: 2.25rem;

  & .custom-control-label {
    padding-left: .75rem;
    padding-top: 0.15rem;

    &::before {
      border-radius: 1rem;
      height: 1.5rem;
      width: 2.5rem;
    }

    &::after {
			border-radius: .65rem;
      height: calc(1.5rem - 4px);
      width: calc(1.5rem - 4px);
    }
  }
	
	.custom-control-input:checked ~ .custom-control-label::after{
  transform: translateX(1rem);
	}
}

// Add class `.custom-switch-xl` to a `custom-switch`
.custom-switch.custom-switch-xl {
  padding-bottom: 1rem;
	padding-left: 2.25rem;

  & .custom-control-label {
    padding-left: 2rem;
  	padding-top: 0.5rem;
  
    &::before {
      border-radius: 1rem;
      height: 2rem;
      width: 3.5rem;
    }

    &::after {
      border-radius: 2rem;
      height: calc(2rem - 4px);
      width: calc(2rem - 4px);
    }
  }
	
	.custom-control-input:checked ~ .custom-control-label::after {
  transform: translateX(1.5rem);
	}
}
    </style>
  

{% endblock stylesheets %}

{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Wines and Drinks</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Manage Inventory</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      
      <div class="modal" id="myModal">
        <div class="modal-dialog">
          <div class="modal-content">
      
            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Add Items</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
      
            <!-- Modal body -->
            <div class="modal-body">
              {% load crispy_forms_tags %}
                  <form action="../redirectadditem" method="post">
                    {% csrf_token %}
                    {{ form | crispy}}
                    <input type="submit" value="Submit">
                  </form>
            </div>
      
          </div>
        </div>
      </div>
      <!-- Default box -->
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-1">
          <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#myModal">
            Add Item
          </button>
        </div>
        
        <div class="col-md-9">
        
        
        <div class="container-fluid">

            <div class="row">
              {% load thumbnail %}
                {% for item in items %}
                <div class="card bg-transparent text-center col-3 ml-4">
                    <img class="img-top" src="{% thumbnail item.product.image 0x150 %}" alt="{{item.product.name}}">
                    <div class="card-img-overlay">
                        <h5 class="card-title">{{item.product.name}}</h5>
                    </div>
                    <div class="card-body">
                      <form action="../redirectinventory" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="productid" value="{{item.id}}">
                        <div class="custom-control custom-switch custom-switch-lg">
                            <input type="checkbox" name="status" class="custom-control-input" id="p{{item.id}}" {% if item.status %} checked {% endif %} onchange="this.form.submit()">
                            <label class="custom-control-label" for="p{{item.id}}" >{{item.product.name}}</label>
                        </div>
                      </form>
                      <form action="../redirectremoveitem" method="POST">
                      {% csrf_token %}
                      <input type="hidden" name="itemid" value="{{item.id}}">
                      <button class="btn btn-danger btn-block" value="Remove Item">Remove Item</button>
                      </form>
                    </div>
                </div>
                {% empty %}

                {% endfor %}
            </div>
            </div>
            
        </div>
        <div class="col-md-1"></div>
        </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>

{% endblock javascripts %}

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    {% block javascript %}
    {% endblock javascript %}
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <div class="container">
        <a href="{% url 'store:product_list' %}" class="navbar-brand">FreshExpress</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navigation">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a href="{% url 'store:product_list' %}" class="nav-link">
                <i class="fa fa-shopping-bag fa-lg mr-1"></i> Store
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'store:categories_list' %}" class="nav-link">
                <i class="fa fa-shopping-basket fa-lg mr-1"></i> Categories
              </a>
            </li>
          </ul>
          <form action="/" class="inline-form mr-md-2 ml-auto">
            <div class="input-group">
              <input
                required
                type="text"
                name="name"
                placeholder="Search items"
                class="form-control"
              />
              <div class="input-group-append">
                <button type="submit" class="btn-success btn btn-sm">
                  <i class="fa fa-search fa-lg"></i>
                </button>
              </div>
            </div>
          </form>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'orders:my' %}" class="nav-link">
                <i class="fa fa-truck fa-lg mr-1"></i> My Orders
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'cart:cart_details' %}" class="nav-link">
                <i class="fa fa-shopping-cart fa-lg"></i>
                <span class="badge badge-secondary">
                  {% if cart %} {{cart|length}} {% else %} 0 {% endif%}
                </span>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a
                href="#"
                class="nav-link dropdown-toggle mb-0"
                data-toggle="dropdown"
              >
                {{request.user}}
              </a>
              <div class="dropdown-menu">
                <a href="{% url 'profile'%}" class="dropdown-item">Profile</a>
                <a href="{% url 'password_change'%}" class="dropdown-item">
                  Change Password
                </a>
                {% load merchant_tag %}
                {% if request.user|ismerchant %}
                <a href="{% url 'shopadmin:receivedorders'%}" class="dropdown-item">Received Orders</a>
                <a href="{% url 'shopadmin:acceptedorders'%}" class="dropdown-item">Accepted Orders</a>
                <a href="{% url 'shopadmin:inventory'%}" class="dropdown-item">Inventory</a>
                <a href="{% url 'shopadmin:redirectstore'%}" class="dropdown-item">Update Store</a>
                {% endif %}
                <a href="{% url 'address'%}" class="dropdown-item">Address</a>
                <a href="{% url 'logout' %}" class="dropdown-item">Logout</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a href="{% url 'login' %}" class="nav-link">
                <i class="fa fa-sign-in fa-lg"></i> Login
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'register' %}" class="nav-link">
                <i class="fa fa-user-plus fa-lg"></i> Register
              </a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% if messages %}
      <div class="alert alert-success my-2">
        {% for message in messages %} {{message}} {% endfor %}
      </div>
      {% endif %} {% block content %} {% endblock content %}

      <div class="modal" id="supportmodal">
        <div class="modal-dialog">
          <div class="modal-content">
      
            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Support Query</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
      
            <!-- Modal body -->
            <div class="modal-body">
              {% load crispy_forms_tags %}
                  <form action="{% url 'help' %}" method="post">
                    {% csrf_token %}
                    <!-- Form Name -->
                    
                    Name : <input type="text" value=" " name="username" class="form-control input-md" ><br>
                    Email : <input type="text" value=" " name="email" class="form-control input-md" ><br>
                    Enter your question : <input type="textarea" rows="5" cols="50" value=" " name="queries" class="form-control input-lg"><br>
                    <input type="submit" value="Submit" class="btn btn-primary">
                  </form>
            </div>
      
          </div>
        </div>
      </div>
      <br><br><br><br>
      <button type="button" class="btn btn-dark btn-block fixed-bottom" data-toggle="modal"  data-target="#supportmodal">
        Help and Support
      </button>

    </div>
  </body>
</html>

accounts/templates/index4.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard2 {% endblock %} 

<!--{% block body_class %} sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed {% endblock body_class %}-->

{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="/static/assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">
  .strikethrough:checked + span{
    text-decoration:line-through
  }

{% endblock stylesheets %}
{% block content %}
<div class="content-wrapper">
<div class="container-fluid">
    <!-- /.card-header -->
    <h1>List of Orders</h1>
    <div class="card-body p-0">
      <div class="table-responsive">
        <table class="table m-0 " border="0" id="tab1">
            <colgroup span="1"></colgroup>
          <tr>
            <th scope="rowgroup">Order ID</th>
            <th colspan="1">List of Items</th>
            <th>Status</th>
          </tr>
          
          <ol class="todo-list" data-widget="todo-list">
          <tbody>
              {% for key,vallist in li.items %}
          <tr>
              <div class="row">
                  <div class="col-4 col-md-2">
            <td scope="rowgroup"><a href="pages/examples/invoice.html">{{key}}</a></td></div>
            <div class="col-6 col-md-4">
                <td colspan="1">
                {% for val in vallist %}
                <div class="icheck-success d-inline ml-2">
                    <input type="checkbox" id="item1" class="strikethrough" value="2">
                    <label for="todoCheck1"></label>
                </div>
                <span class="text">{{val}}</span>
                {% endfor %}
                </td>
            </div>
            <div class="col-6 col-md-4">
                <td>
                    <input class="btn btn-sm btn-success"  onClick="myfunction()" type="submit" id="accept" value="Accept">
                    <input class="btn btn-sm btn-danger" type="submit" id="reject" value="Reject">
                    <p id="demo"></p>

                </td>
                </div>
                </div>

          </tr>
          {% endfor %}
        </ol>
          </tbody>
        </table>
      </div>
      <!-- /.table-responsive -->
    </div>
    <!-- /.card-body -->
    <p id ="displayvalues"></p>
    <div class="card-footer clearfix">
      <a href="javascript:void(0)" class="btn btn-sm btn-info float-left">Home</a>
      <a href="javascript:void(0)" class="btn btn-sm btn-secondary float-right">Accept All Orders</a>
    </div>
    <!-- /.card-footer -->
  </div>
</div>
</div>
</div>
<script>
    function myFunction() {
      alert("hello");
     /* var selected=new Array();
      var chkbox=document.getElementById("tab1");
      var selchk=chkbox.getElementsByTagName("input");
      for(var i=0;i<selchk.length;i++){
        if(selchk[i].checked){
          selected.push(selchk[i].value);
        }
      }
      if(selected.length>0){
        document.getElementById("displayvalues").innerhtml=selected;
      }*/
    }
    </script>
  
  {% endblock content %}

accounts/templates/index5.html
<!DOCTYPE html>
<head>
    <title>helo</title>


    <body>
        {% for i in result%}
    <h1>{{{ i }}</h1>
    {% endfor %}
    </body>
</head>

accounts/templates/useraddress.html
{% extends 'base.html' %} {% load thumbnail %} {% block title %} Store Info {% endblock title %} 
{% block javascript %}

{% endblock javascript %}
{% block content %}
{% load crispy_forms_tags %}
<br><br>
<h3> Update your address details. </h3>

<form action="" method="post">
                {% csrf_token %}
                {{ form | crispy}}
    <input type="submit" value="Update/Add" class="btn btn-success">
</form>

{% endblock content %}